### ISSUE TITLE
rpath for the LDFLAGS

### ISSUE THREAD

**Issue by mhsieh** [PacificBiosciences/pitchfork#146]
So binaries might eventually be independent from LD_LIBRARY_PATH

**Comment by pb-cdunn** [comment]
This is really long term. **Spack** adds RPATH, and if that's what we want, we could use **Spack** instead of pitchfork. But the point of pitchfork is to keep things simple.

**Comment by mhsieh** [comment]
CC @nlhepler

**Comment by nlhepler** [comment]
rpath (with $ORIGIN, on linux at least), would let us drop LD_LIBRARY_PATH and wrappers. Spack using RPATH doesn't mean we need to drop pitckfork and use Spack... that doesn't logically follow. RPATH is a general construct for an application telling the linker where to search for dynamic libraries first. If those occur in $ORIGIN/../lib then we should just add those as default linker flags for C/C++ projects, especially/exclusively if they installed dependencies.

**Comment by mjhsieh** [comment]
We will need to see various ways to tell builder to add LDFLAGS="-Wl,-rpath=$ORIGIN/../lib", but I guess it would be easy for autoconfig, not sure bout cmake, though.

**Comment by pb-cdunn** [comment]
I'm saying that setting RPATH is extra work. LD_LIBRARY_PATH=onedirtorulethemall is easy. I've done all this before, including with `$ORIGIN`, cross-platform support, RPATH vs. RUNPATH, etc.

If you think you need RPATH, then you should not be using a PREFIX directory. That's a completely different animal, a so-called ["functional package manager"](https://news.ycombinator.com/item?id=11096906) (and click "parent" for more discussion). You will begin to reinvent the wheel, which is why you should be considering an off-the-shelf alternative. It's a much bigger job than you seem to realize. As a reasonable compromise between flexibility and effort, I'd recommend either [EasyBuild](http://easybuild.readthedocs.org/en/latest/Introduction.html) (which generates **module** files) or [Spack](http://software.llnl.gov/spack/packaging_guide.html) (which relies on RPATH but also creates **module** files) for everything that rarely changes, and **pitchfork** for our modules under development. It seems like we'd get the best of both worlds.

On the other hand, if you really want one PREFIX tree with multiple library versions, I would try to use [shared-library *versioning*](http://www.kaizou.org/2015/01/linux-libraries/) instead of RPATH. If you have two versions of htslib, then call them htslib.so.1 and htslib.so.2. Then they can live in the same tree. When you build an executable, provide one of those "sonames" (which could be symlinked to htslib.so.1.y.z). That will go into the DT_NEEDED field of the ELF header.

But if you guys volunteer to inject RPATH into every C++ build, knock yourselves out.

* https://www.nsc.liu.se/~torbenr/presentations/EasyBuild-intro-Espoo_20150506.pdf
* http://www.rce-cast.com/Podcast/rce-103-easybuild.html (Skip to 5:20.)
* https://groups.google.com/forum/#!topic/hashdist/CcsjgeaR7Zo (spack vs. hastdist, which might be a little better for developers)

**Comment by mhsieh** [comment]
I ate all the low hanging fruits. close this for now.
