### ISSUE TITLE
Work with gcc newer than version 5

### ISSUE THREAD

**Issue by mhsieh** [PacificBiosciences/pitchfork#265]
blasr doesn't build on gcc/6 or gcc/7

**Comment by pb-cdunn** [comment]
Well, sort of. Actually, blasr builds fine on gcc/6 and 7 if configured properly. But we cannot use `HFD5_INC=/usr/include`, as we then put that into the include PATH via `-isystem`. That fails as described here:
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129

So for pitchfork, we will need to avoid `-isystem` in the blasr makefile, since we really cannot avoid using `/usr/include` for pitchfork settings. (Unless you want to strip `/usr/include` from paths that are passed to blasr configure.) I don't think we really need `-isystem` at all, since we are no longer running make-depend (`-MM` etc.), so I'll drop that from blasr. (After lunch...)

**Comment by pb-cdunn** [comment]
Solved in blasr, but watch for this in other repos.
