### ISSUE TITLE
Does pitchfork deploy the latest FALCON build?

### ISSUE THREAD

**Issue by dbrowneup** [PacificBiosciences/pitchfork#302]
Hi,

Yesterday I utilized pitchfork to build unanimity/pbccs and blasr. I see that "pbfalcon" is on the list of build targets, but looking at the FALCON repository, it seems to indicate that FALCON-integrate is the best way to build it. Just wondering if the pbfalcon build in pitchfork is another way to install?

Thanks,
Dan

**Comment by pb-cdunn** [comment]
We try to keep the tip of `master` up-to-date, and that is what pitchfork uses by default. (That can be overridden via `.git/settings.mk`.) That is generally what we use internally too. If something is inconsistent, we'll fix it pretty quickly.

If you want a specific release of FALCON, perhaps because you are working on a journal article, you can use FALCON-integrate. Also, I find that the git-submodules in FALCON-integrate can help to coordinate work if you want to modify our code and submit patches. With pitchfork, by default you can use the repos under `pitchfork/workspace` to edit if necessary.
