### ISSUE TITLE
pitchfork blasr make fails on pbbam

### ISSUE THREAD

**Issue by grgmncr** [PacificBiosciences/pitchfork#397]
I've been trying to install blasr and keep running into errors. I've determined that pitchfork is the best approach for my configuration, but can't seem to overcome this problem. I don't explicitly require pbbam for my project, but can't find an easy way to turn it off that would be analogous to the "./configure --no-pbbam" in the "make" instructions. Is there an obvious fix that I'm missing or an easy way to turn off the pbbam installation?

Thanks,
Greg

**FYI:**
Centos 6.8 final
GCC 4.9.3
HDF5 1.8.16
CMake 3.9
git 2.10.1

**Error Messages:**
```
...
[ 40%] Building CXX object src/CMakeFiles/pbbam.dir/MD5.cpp.o
../../src/MD5.cpp:81:5: error: ‘hts_md5_context’ does not name a type
     hts_md5_context* data_;
     ^
../../src/MD5.cpp: In constructor ‘PacBio::BAM::Md5ContextHelper::Md5ContextHelper()’:
../../src/MD5.cpp:55:11: error: class ‘PacBio::BAM::Md5ContextHelper’ does not have any field named ‘data_’
         : data_(hts_md5_init())
           ^
../../src/MD5.cpp:55:30: error: ‘hts_md5_init’ was not declared in this scope
         : data_(hts_md5_init())
                              ^
../../src/MD5.cpp:57:13: error: ‘data_’ was not declared in this scope
         if (data_ == nullptr)
             ^
../../src/MD5.cpp: In destructor ‘PacBio::BAM::Md5ContextHelper::~Md5ContextHelper()’:
../../src/MD5.cpp:63:25: error: ‘data_’ was not declared in this scope
         hts_md5_destroy(data_);
                         ^
../../src/MD5.cpp:63:30: error: ‘hts_md5_destroy’ was not declared in this scope
         hts_md5_destroy(data_);
                              ^
../../src/MD5.cpp: In member function ‘std::string PacBio::BAM::Md5ContextHelper::Encoded(const string&)’:
../../src/MD5.cpp:69:24: error: ‘data_’ was not declared in this scope
         hts_md5_update(data_, reinterpret_cast<void*>(const_cast<char*>(str.c_str())), str.size());
                        ^
../../src/MD5.cpp:69:98: error: ‘hts_md5_update’ was not declared in this scope
         hts_md5_update(data_, reinterpret_cast<void*>(const_cast<char*>(str.c_str())), str.size());
                                                                                                  ^
../../src/MD5.cpp:72:36: error: ‘hts_md5_final’ was not declared in this scope
         hts_md5_final(digest, data_);
                                    ^
../../src/MD5.cpp:75:38: error: ‘hts_md5_hex’ was not declared in this scope
         hts_md5_hex(hexdigest, digest);
                                      ^
make[4]: *** [src/CMakeFiles/pbbam.dir/MD5.cpp.o] Error 1
make[4]: Leaving directory `/home/gcary/bin/pitchfork/workspace/pbbam/build'
make[3]: *** [src/CMakeFiles/pbbam.dir/all] Error 2
make[3]: Leaving directory `/home/gcary/bin/pitchfork/workspace/pbbam/build'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/gcary/bin/pitchfork/workspace/pbbam/build'
make[1]: *** [/home/gcary/bin/pitchfork/workspace/pbbam/build/lib/libpbbam.so] Error 2
make[1]: Leaving directory `/home/gcary/bin/pitchfork/ports/pacbio/pbbam'
make: *** [pbbam] Error 2

```

**Comment by svm-zhang** [comment]
@grgmncr, I am not a pitchfork developer, but I encountered this error myself as well, when building bax2bam, isoseq_sa4.0, and isoseq_sa3 (my fix below does not fix to build the last tool). 

I'd suggest you to look at the cmake command line (if you scroll a bit upwards this error message), and you would see `-DHTSLIB_INCLUDE_DIRS` and `-DHTSLIB_LIBRARIES` options. To fix it, you'd want to change the htslib paths to the ones under the pitchfork workspace. 

For example, in my case, updating the original command line to this `-DHTSLIB_INCLUDE_DIRS=/opt/pitchfork/workspace/samtools-1.3.1/htslib-1.3.1/htslib` and `-DHTSLIB_LIBRARIES=/opt/pitchfork/workspace/samtools-1.3.1/htslib-1.3.1/libhts.a`, fixed my build issue. 

After this, I simply go to the pbbam folder under workspace, and cmake plus make there myself, and then go back to pitchfork folder and re-run make blasr.

My guess of the problem is that some of the header files are not copied to the src folder under deployment folder (or whatever the prefix you specified).

Hope this helps.

Simo

**Comment by mhsieh** [comment]
interesting... I will take a look.

**Comment by mhsieh** [comment]
Can you try the latest pitchfork checkout again? Thanks!

**Comment by svm-zhang** [comment]
@mhsieh, I just tried with the latest patch, and it worked for pbbam, bax2bam, and blasr. Thanks!

Can I also say when I build isoseq_sa5.0, this problem does not exit, but not for other versions of isoseq.

**Comment by grgmncr** [comment]
@mhsieh that worked for me as well! Thanks so much for the fix!

**Comment by mhsieh** [comment]
@svm-zhang I will need to test-build pbbam in isoseq_sa5.0 as well, the versions in that branch are supposed to be fixed.

**Comment by svm-zhang** [comment]
@mhsieh thanks very much!

**Comment by mhsieh** [comment]
@svm-zhang - The isoseq_sa5.0 branch works for me. See if cleaning up the build help by any chance. ```
make _startover
```

**Comment by svm-zhang** [comment]
@mhsieh thanks so much. It worked for me.

Simo
